'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing personalized feedback on code submissions using AI.
 *
 * It includes:
 * - `getPersonalizedCodeFeedback`: A function to initiate the code feedback process.
 * - `PersonalizedCodeFeedbackInput`: The input type for the `getPersonalizedCodeFeedback` function.
 * - `PersonalizedCodeFeedbackOutput`: The output type for the `getPersonalizedCodeFeedback` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedCodeFeedbackInputSchema = z.object({
  code: z.string().describe('The code submitted by the user.'),
  programmingLanguage: z.string().describe('The programming language of the code.'),
  userSkillLevel: z.string().describe('The skill level of the user (e.g., beginner, intermediate, advanced).'),
  userCodingStyle: z.string().optional().describe('The coding style of the user (e.g., verbose, concise).'),
});
export type PersonalizedCodeFeedbackInput = z.infer<typeof PersonalizedCodeFeedbackInputSchema>;

const PersonalizedCodeFeedbackOutputSchema = z.object({
  feedback: z.string().describe('Personalized feedback on the code submission as 2-3 concise bullet points in markdown format.'),
  rating: z.number().describe('A rating of the code submission (e.g., 1-5).'),
  readability: z.number().describe('A rating for readability (1-5).'),
  logic: z.number().describe('A rating for logic (1-5).'),
  optimization: z.number().describe('A rating for optimization (1-5).'),
  maintainability: z.number().describe('A rating for maintainability (1-5).'),
  codeExplanation: z.string().describe('An explanation of the provided code, tailored for a beginner, presented in a line-by-line or logical block format for readability.'),
  aiDetection: z.object({
    likelihood: z.number().describe('The likelihood (0-100) that the code was generated by an AI.'),
    reasoning: z.string().describe('A brief explanation for the AI detection likelihood, highlighting patterns like overly generic variable names, perfect comments, or common AI solution structures.')
  }).describe('An analysis of whether the code appears to be AI-generated.')
});
export type PersonalizedCodeFeedbackOutput = z.infer<typeof PersonalizedCodeFeedbackOutputSchema>;

export async function getPersonalizedCodeFeedback(input: PersonalizedCodeFeedbackInput): Promise<PersonalizedCodeFeedbackOutput> {
  return personalizedCodeFeedbackFlow(input);
}

const personalizedCodeFeedbackPrompt = ai.definePrompt({
  name: 'personalizedCodeFeedbackPrompt',
  input: {schema: PersonalizedCodeFeedbackInputSchema},
  output: {schema: PersonalizedCodeFeedbackOutputSchema},
  prompt: `You are an AI code reviewer providing personalized feedback on code submissions.

  Your goal is to provide feedback that is friendly, easy to understand, human-like, and beginner-safe.
  Avoid robotic or harsh wording.

  Consider the user's skill level and coding style when providing feedback.

  Programming Language: {{{programmingLanguage}}}
  User Skill Level: {{{userSkillLevel}}}
  User Coding Style: {{{userCodingStyle}}}

  Code:
  {{{
    code
  }}}

  1.  **Provide Feedback:** Generate personalized feedback as 2-3 concise bullet points in markdown format. The feedback must include specific suggestions for improvement.
  2.  **Explain the Code:** Create a section that explains the provided code. This explanation should be tailored for a complete beginner. Break it down line-by-line or in logical blocks, ensuring it is not a single long paragraph. Use simple terms and real-life analogies to make the concepts easy to grasp. Format it clearly. Do not use any markdown formatting like bolding in the explanation.
  3.  **Provide Ratings:** Assign a rating (1-5) for the code submission overall. Also, provide ratings (1-5) for readability, logic, optimization, and maintainability.
  4.  **AI-Generated Code Detection:** Analyze the submitted code to determine the likelihood that it was written by an AI. Consider factors like overly generic variable names, perfect but slightly unnatural comments, use of common patterns seen in AI-generated code, and overall code structure. Provide a likelihood percentage (0-100) and a brief reasoning for your assessment.
`,
});

const personalizedCodeFeedbackFlow = ai.defineFlow(
  {
    name: 'personalizedCodeFeedbackFlow',
    inputSchema: PersonalizedCodeFeedbackInputSchema,
    outputSchema: PersonalizedCodeFeedbackOutputSchema,
  },
  async input => {
    const {output} = await personalizedCodeFeedbackPrompt(input);
    return output!;
  }
);
